// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufvratayzdenrzzbekxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmdnJhdGF5emRlbnJ6emJla3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczODMwMDIsImV4cCI6MjA2Mjk1OTAwMn0.Rr3xAAokv8C5ZO0pRNgGxwzx0WQlR6PoBqaN4BOG6jg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);